### ISSUE TITLE
camo proxy dies when NBB is reloaded, EADDRINUSE error

### ISSUE THREAD

**Issue by bdharrington7** [minora-oss/nodebb-plugin-camo#8]
Hi, I just noticed that this plugin will crash out when NodeBB is reloaded.

```
[cluster] Reloading...

3/9 15:54 [21142] - [32minfo[39m: [Camo]: Starting CamoProxy...
3/9 15:54 [21142] - [32minfo[39m: [CamoProxy]: SSL-Proxy running on 8082 with pid:21357 version:2.3.0.

3/9 15:54 [21142] - [33mwarn[39m: [CamoProxy]: events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8082
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1236:14)
...

3/9 15:54 [21142] - [32minfo[39m: [Camo]: CamoProxy is dead.
```

**Comment by yariplus** [comment]
The child process was disconnected from the main process.

You'll need to do `top` to find the process and `kill ###`

Camo will still work with this error. It just keeps running when NodeBB stops. Should be fixed now.
